@base-url = http://localhost:8080
@auth-url = /api/auth
@task-url = /api/tasks
@token = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJHaGVyZW1pYWgiLCJpYXQiOjE3ODAwNDQwNjcsImV4cCI6MTc4MDEzMDQ2N30.XHjN7DQq00ipyCdW9fTC8k9pE_IC1XVFf-owHRjpBBaRu20S8hSKwai7JDaIzqQlNsJkwrVYr1CQ4W9IIU6_nw

### Index route
GET {{base-url}}
Content-Type: application/json

### Login
POST {{base-url}}{{auth-url}}/login
Content-Type: application/json

{ "username": "Gheremiah", "password": "Passw0rd@123" }


### Register
POST {{base-url}}{{auth-url}}/signup
Content-Type: application/json

{ "username": "Gheremiah", "password": "Passw0rd@123", "email": "gheremiahwhole@gmail.com", "roles": ["user"] }

### Get all tasks (requires authentication)
GET {{base-url}}{{task-url}}
Authorization: Bearer {{token}}
Content-Type: application/json


### Create a new task (requires authentication)
POST {{base-url}}{{task-url}}
Authorization: Bearer {{token}} 
Content-Type: application/json

{ "title": "Task 3", "description": "Task 3 description" }


### Get a specific task by ID (requires authentication)
GET {{base-url}}{{task-url}}/1
Authorization: Bearer {{token}}
Content-Type: application/json


### Update a task by ID (requires authentication)
PUT {{base-url}}{{task-url}}/2
Authorization: Bearer {{token}}
Content-Type: application/json

{ "title": "Updated Task 3", "description": "Task 3 has been updated" }


### Delete a task by ID (requires administration role)
DELETE {{base-url}}{{task-url}}/1
Authorization: Bearer {{token}}
Content-Type: application/json