spring.application.name=JavaApp

# Server configuration
server.port=8080

# Application name
# Logging
logging.level.com.app.javaapp=DEBUG

# Show more details in error responses
server.error.include-message=always
server.error.include-binding-errors=always

# Custom property (just for demonstration)
app.name=Task Manager
app.version=1.0.0